name: full_screen_helper
description: A Flutter package to handle full screen intent notifications for ride-hailing apps.
version: 0.0.1
homepage: https://github.com/Lovich69/full_screen_helper # Required!

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  # Add the dependencies your helper code needs
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^17.0.0
  url_launcher: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
